apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voting-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: development 
  source:
    path: helm
    repoURL: https://github.com/gonzaloacosta/voting-app.git
    targetRevision: HEAD 
    helm:
      values: |
        result:
          image:
            tag: develop
          ingressHost: result.develop.192.168.64.6.nip.io
        vote:
          image:
            tag: develop
          ingressHost: vote.develop.192.168.64.6.nip.io
        worker:
          image:
            tag: develop
      version: v3
  destination:
    namespace: development 
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
